In [138]:
import torch

Tensor datatypes

In [139]:
#  Type of tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32, device='cuda', requires_grad= False)
print(float_32_tensor.dtype)
float_16_tensor = float_32_tensor.to(torch.float16)
print(float_16_tensor.dtype)


print(float_16_tensor * float_32_tensor)

long_tensor = torch.tensor([3, 6, 9], dtype=torch.long, device='cuda', requires_grad= False)
long_tensor = long_tensor * float_32_tensor
print(long_tensor.dtype)

torch.float32
torch.float16
tensor([1., 4., 9.], device='cuda:0')
torch.float32


Getting info from tensor

In [140]:
some_tensor = torch.randn(4, 5)
some_tensor

tensor([[ 0.5083, -2.3724, -1.6927, -0.2020,  0.7623],
        [-0.9868, -0.3699, -0.7381, -0.8717,  0.0082],
        [ 0.2400,  0.2311,  0.5390,  0.1974,  0.0810],
        [-0.0046,  0.9247,  0.1101,  1.3842,  0.5333]])

In [141]:
print(some_tensor)
print(f"tensor size:\t", some_tensor.size())
print(f"tensor shape:\t", some_tensor.shape)
print(f"tensor dimensions:\t", some_tensor.ndim)
print(f"tensor shape:\t", some_tensor.shape)
print(f"Device tensor is on:\t", some_tensor.device)
some_tensor = some_tensor.to('cuda')
print(f"Device tensor is on:\t", some_tensor.device)

tensor([[ 0.5083, -2.3724, -1.6927, -0.2020,  0.7623],
        [-0.9868, -0.3699, -0.7381, -0.8717,  0.0082],
        [ 0.2400,  0.2311,  0.5390,  0.1974,  0.0810],
        [-0.0046,  0.9247,  0.1101,  1.3842,  0.5333]])
tensor size:	 torch.Size([4, 5])
tensor shape:	 torch.Size([4, 5])
tensor dimensions:	 2
tensor shape:	 torch.Size([4, 5])
Device tensor is on:	 cpu
Device tensor is on:	 cuda:0


Tensor operation
- Addition
- Substraction
- Mulitiplication
- Division
- Matrix multiplication

In [142]:
tensor = torch.tensor([1, 2, 3])
tensor+= 10
tensor
tensor *= 3
tensor
tensor -= 6
tensor = tensor / 3
tensor

tensor([ 9., 10., 11.])

In [143]:
# Matrix Multiplication
# 1. PyTorch has a built in function for matrix multiplication torch.matmul()
# 2. The @ operator performs matrix multiplication in PyTorch (and Python)
tensor_A = torch.tensor([1, 2, 3])
print(tensor_A * tensor_A)

# Matrix multiplication
%time torch.matmul(tensor_A, tensor_A)
A = torch.randn(1000, 1000)
B = torch.randn(1000, 1000)
%time print("CPU time",torch.matmul(A, B))
A = A.to('cuda')
B = B.to('cuda')

import time

torch.cuda.synchronize()
start = time.time()

C = torch.matmul(A, B)

torch.cuda.synchronize()
end = time.time()

print("GPU matmul time:", end - start)

tensor([1, 4, 9])
CPU times: total: 0 ns
Wall time: 0 ns
CPU time tensor([[-40.3030,  19.9081, -25.4235,  ...,  18.4020,  -3.4891,  27.4160],
        [-43.6576,  59.1825, -28.9668,  ..., -18.4314,   5.1466, -35.5589],
        [  1.7441, -41.1047,  -0.2558,  ...,  48.8583, -23.7307, -12.0074],
        ...,
        [-22.0132,  17.6807, -26.2999,  ..., -23.3483,  90.4296,  -5.6244],
        [ 21.5044,  14.1511, -28.0474,  ..., -36.1756,  50.7357, -27.1935],
        [ 28.4638, -14.1231,  20.4940,  ...,   6.6491,  29.3228,  19.2368]])
CPU times: total: 0 ns
Wall time: 4.18 ms
GPU matmul time: 0.0838010311126709


Matrix multiplication
- INNER dimension must match
- Result of matrix has the shape of OUTER dimension

In [144]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
tensor_A.shape, tensor_B.shape
torch.mm(tensor_A, tensor_B.T).shape
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Tensor aggregation

In [145]:
x = torch.arange(0.0, 100, step=10)
torch.min(x), torch.max(x), torch.mean(x), torch.sum(x)

(tensor(0.), tensor(90.), tensor(45.), tensor(450.))

In [146]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* View - Return a view of an input tensor of a certain shape but doesn't change the original tensor.
* Reshaping - Reshapes an input tensor to a defined shape.
* Stacking - Combines multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeezing - Removes all 1 dimensions from a target tensor.
* Unsqueezing - Adds a 1 dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted in a certain way.

In [147]:
import torch
x = torch.arange(0.0, 12.0)
x, x.shape

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 torch.Size([12]))

In [148]:
# Add an extra dimension to x
x_reshaped = x.reshape(3, 4)
x_reshaped, x_reshaped.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]))

In [149]:
# Change the view of x
z = x.view(3, 4)
z, z.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]))

In [150]:
# Changing z changes x 
z[:,0] = 5
z, x

(tensor([[ 5.,  1.,  2.,  3.],
         [ 5.,  5.,  6.,  7.],
         [ 5.,  9., 10., 11.]]),
 tensor([ 5.,  1.,  2.,  3.,  5.,  5.,  6.,  7.,  5.,  9., 10., 11.]))

In [151]:
# Stack tensors on top of each other 
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[ 5.,  1.,  2.,  3.,  5.,  5.,  6.,  7.,  5.,  9., 10., 11.],
         [ 5.,  1.,  2.,  3.,  5.,  5.,  6.,  7.,  5.,  9., 10., 11.],
         [ 5.,  1.,  2.,  3.,  5.,  5.,  6.,  7.,  5.,  9., 10., 11.],
         [ 5.,  1.,  2.,  3.,  5.,  5.,  6.,  7.,  5.,  9., 10., 11.]]),
 torch.Size([4, 12]))

In [152]:
# torch.squeeze() removes all 1-dimensions from a tensor
tensor = torch.arange(1, 10)
tensor = sq_tensor.reshape(1,9)
print(f"Previous tensor: {tensor}") 
print(f"Previous shape: {tensor.shape}")
sq_tensor = tensor.squeeze()
print(f"Squeezed tensor: {sq_tensor.squeeze()}")
print(f"Squeezed shape: {sq_tensor.shape}")

NameError: name 'sq_tensor' is not defined

In [ ]:
# torch.unsqueeze() adds a 1-dimension to a tensor at a specified dim
print(f"Previous tensor: {sq_tensor}")
print(f"Previous shape: {sq_tensor.shape}")

# Add an extra dimension to the end of the tensor
unsqueezed_tensor = sq_tensor.unsqueeze(dim=1)
print(f"Unsqueezed tensor: {unsqueezed_tensor}")
print(f"Unsqueezed shape: {unsqueezed_tensor.shape}")

Previous tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
Unsqueezed tensor: tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Unsqueezed shape: torch.Size([9, 1])


In [ ]:
# torch.permute() rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size=(1080, 1920, 3)) # [Height, width, color_channels]

# Premute the original tensor to rearrange the dimensions to [color_channels, height, width]
x_permuted = x_original.permute(2, 0, 1)

print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_permuted.shape}")

Original shape: torch.Size([1080, 1920, 3])
Permuted shape: torch.Size([3, 1080, 1920])


## Indexing (select data from tensor)

In [ ]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# indexing on different dimensions
x[0], x[0][0], x[0][1][2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(6))

In [ ]:
x[:,0], x[:,:,1], x[:,1,1], x[0,0,:], x[:,2,2], x[:,:,2]


(tensor([[1, 2, 3]]),
 tensor([[2, 5, 8]]),
 tensor([5]),
 tensor([1, 2, 3]),
 tensor([9]),
 tensor([[3, 6, 9]]))

## Pytorch & Numpy

* Data in Numpy --> Pytorch tensor

In [ ]:
import torch
import numpy as np
# Numpy > Tensor
array = np.array([[1., 2, 3], [4, 5, 6], [7, 8, 9]])
tensor64 = torch.from_numpy(array)

tensor32 = torch.from_numpy(array).to(torch.float32)
tensor64, tensor64.dtype, tensor64.shape, tensor32, tensor32.dtype, tensor32.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]], dtype=torch.float64),
 torch.float64,
 torch.Size([3, 3]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32,
 torch.Size([3, 3]))

In [158]:
# Tensor > Numpy

tensor = torch.ones((3, 4))

numpy_array = tensor.numpy()
numpy_array, numpy_array.shape

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32),
 (3, 4))

## Reproducbility (Random SEED)

`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again`

In [170]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

torch.manual_seed(42)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(42)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)


tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [174]:
!nvidia-smi

Fri Apr 17 16:42:01 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.97                 Driver Version: 595.97         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   48C    P8             25W /  198W |    1687MiB /   8192MiB |     16%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
torch.cuda.is_available()
devaice = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {devaice}, cuda: {torch.cuda.get_device_name(0)}")


Using device: cuda, cuda: NVIDIA GeForce RTX 3070


In [3]:
tensor = torch.tensor([1, 2, 3], device='cuda')
print(tensor)
tensor = tensor.cpu()
print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3]) cpu


In [19]:
torch.manual_seed(0)
tensor_A = torch.rand(size=(7, 7), device='cuda')
print(tensor.shape)
torch.manual_seed(0)
tensor_B = torch.rand(size=(1,7), device='cuda')
mul_tensor = torch.matmul(tensor_A, tensor_B.T)
print(mul_tensor, mul_tensor.shape)

torch.Size([7, 7])
tensor([[3.0122],
        [1.3752],
        [1.7349],
        [1.6234],
        [2.8933],
        [1.8644],
        [1.1851]], device='cuda:0') torch.Size([7, 1])
